name: MSBuild

permissions:
  contents: write

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - closed
  create:
    tags:
      - '*'

env:
  SOLUTION_FILE_PATH: ChessGame.sln
  BUILD_CONFIGURATION: Release
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2

      with:
        name: release-build
        path: x64\Release\

    - name: Release with Notes
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1

      with:
        files: |
          .\x64\Release\engine.exe
